import { CalendarEvent } from "@/types/event";

export const DASHBOARD_STATS = [
    { label: "Upcoming Events", value: "0" },
    { label: "Total Events", value: "0" },
    { label: "Pending Estimates", value: "0" },
    { label: "Open Enquiries", value: "0" },
    { label: "Client Bills", value: "0" },
    { label: "Active this week", value: "0" },
];

export const SAMPLE_EVENTS: CalendarEvent[] = [
    {
        id: "1",
        title: "IBM Annual Day",
        date: "2026-03-25",
        client: "IBM Corp",
        location: "Grand Ballroom",
        status: "open",
        asignee: "John Doe",
        currentTask: "Stage setup",
    },
    {
        id: "2",
        title: "Experion Team Meet",
        date: "2026-03-28",
        client: "Experion Technologies",
        location: "Conference Hall A",
        status: "open",
        asignee: "Priya Nair",
        currentTask: "Send invites",
    },
    {
        id: "3",
        title: "Product Launch",
        date: "2026-03-12",
        client: "TechStart Inc",
        location: "Convention Center",
        status: "completed",
        asignee: "Alan Smith",
        currentTask: "Event wrap-up",
    },
    {
        id: "4",
        title: "Annual Gala Dinner",
        date: "2026-04-05",
        client: "Azure Foundation",
        location: "Lakeside Resort",
        status: "open",
        asignee: "Sara Lee",
        currentTask: "Menu finalization",
    },
    {
        id: "5",
        title: "Team Building Retreat",
        date: "2026-03-21",
        client: "Innovate LLC",
        location: "Mountain Lodge",
        status: "open",
        asignee: "Carlos Mendez",
        currentTask: "Transport arrangement",
    },
    {
        id: "6",
        title: "Startup Demo Day",
        date: "2026-04-11",
        client: "VentureHub",
        location: "Tech Park",
        status: "open",
        asignee: "Maya Tan",
        currentTask: "Tech checks",
    },
    {
        id: "7",
        title: "Wedding Reception",
        date: "2026-03-30",
        client: "Alexander Family",
        location: "Rose Garden Venue",
        status: "cancelled",
        asignee: "N/A",
        currentTask: "N/A",
    },
];
